#配置服务端口号 本服务相当于service1服务器，进行逻辑操作
server:
  port: 9002
spring:
  #配置服务名称
  application:
    name: mybatis2
  #配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test11?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
      base-url: http://localhost:9000
      enabled: true
  sleuth:
      #监控开关
      enabled: true
      #采样率
      sampler:
        percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #配置配置注册中心显示服务的ip地址和端口
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    appname: mybatis2
#配置mybatis mapper文件映射地址
mybatis:
  mapper-locations: classpath:dao/*.xml
#每次重启刷新配置文件
management:
  security:
    enabled: false
endpoints:
  refresh:
    sensitive: false

