server:
  port: 8761
spring:
  application:
    name: eureka

eureka:
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

endpoints:
  refresh:
    sensitive: false